name: linux-panda
version: 4.4.19
summary: A PandaBoard kernel built from source
description: This is the reference kernel for PandaBoard and PandaBoard ES
type: kernel
confinement: devmode
architectures: [armhf]

parts:
    kernel:
        plugin: kernel
        source: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
        source-tag: v4.4.19
        source-type: git
        kdefconfig: [omap2plus_defconfig]
        kconfigs:
            - CONFIG_LOCALVERSION="-panda"
            - CONFIG_DEBUG_INFO=y
            - CONFIG_SQUASHFS=y
            - CONFIG_SQUASHFS_XZ=y
            - CONFIG_DEVPTS_MULTIPLE_INSTANCES=y
            - CONFIG_FB_PRE_INIT_FB=y
            - CONFIG_FB_OMAP2=y
            - CONFIG_RTC_DRV_TWL4030=y
            - CONFIG_USB=y
            - CONFIG_USB_KBD=y
            - CONFIG_USB_MOUSE=y
            - CONFIG_USB_OHCI_HCD=y
            - CONFIG_USB_EHCI_HCD=y
            - CONFIG_USB_STORAGE=y
            - CONFIG_OMAP2_DSS=y
            - CONFIG_DISPLAY_CONNECTOR_DVI=y
            - CONFIG_DISPLAY_CONNECTOR_HDMI=y
            - CONFIG_DISPLAY_PANEL_DPI=y
            - CONFIG_SECURITY_APPARMOR=y
            - CONFIG_SECURITY_APPARMOR_BOOTPARAM_VALUE=1
            - CONFIG_DEFAULT_SECURITY_APPARMOR=y
            - CONFIG_AUDIT=y
        kernel-image-target: zImage
        kernel-device-trees:
            - omap4-panda-a4
            - omap4-panda
            - omap4-panda-es
        build-packages: [crossbuild-essential-armhf, bc, kmod, cpio]
    wl1xxx-firmware:
        plugin: dump
        source: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
        source-type: git
        organize:
            ti-connectivity: lib/firmware/ti-connectivity
