name: mir-server
# for convenience, make version match mir
version: 0.19
summary: A minimalistic Mir server snap
description: This Mir server uses the default settings that the Mir server library provides.
icon: mir.png
type: app

apps:
  mir-server:
    command: bin/run-mir
    daemon: simple
    uses:
      - migration-one
      - migration-two
#    security-template: unconfined
uses:
  migration-one:
    type: migration-skill
    security-template: display-server
  migration-two:
    type: migration-skill
    security-template: unix-listener
parts:
  server:
    plugin: cmake
    source: src
    build-packages:
      - libc6-dev
      - pkg-config
    stage-packages:
      - libmirserver-dev
      - mir-graphics-drivers-desktop
glue:
  plugin: copy
  files:
    run-mir: bin/run-mir
