name: mir-server
#for convenience, make the version matches mir
version: 0.19
summary: A minimalistic Mir server snap
description: This Mir server uses the default settings that the Mir server library provides.
icon: mir.png
type: app

apps:
  mir-server:
    command: bin/run-mir
    daemon: simple
    caps:
      - display-server
      - unix-listener
#    security-template: unconfined
parts:
    server:
        plugin: cmake
        source: src
        stage-packages:
            - libmirserver-dev
            - mir-graphics-drivers-desktop
    glue:
        plugin: copy
        files:
            run-mir: bin/run-mir
